# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'reactnativeaudiorecorder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for react-native-audio-recorder
  pod 'AudioKit', '~> 4.2'
  pod 'SwiftyJSON', '~> 4.1'
end

def change_lines_in_file(file_path, &change)
    print "Fixing #{file_path}...\n"

    contents = []

    file = File.open(file_path, 'r')
    file.each_line do | line |
        contents << line
    end
    file.close

    File.open(file_path, 'w') do |f|
        f.puts(change.call(contents))
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
        end
    end
end
